config/routes.rb
Proyecto::Application.routes.draw do
  resources :camaras

  match "admin/camaras", to: "camaras#index"
  resources :identities
  root to: "sessions#new"
  match "/auth/:provider/callback", to: "sessions#create"
  match "/auth/failure", to: "sessions#failure"
  match "/logout", to: "sessions#destroy", :as => "logout"

end

app/models/camara.rb
class Camara < ActiveRecord::Base
  attr_accessible :ubicacion
end

app/models/identity.rb
class Identity < OmniAuth::Identity::Models::ActiveRecord
  #attr_accessible :email, :name, :password_digest
  validates_presence_of :name
  validates_uniqueness_of :email
  validates_format_of :email, :with => /^[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}$/i
end

app/models/pagina.rb
class Pagina < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/user.rb
class User < ActiveRecord::Base
  #attr_accessible :provider, :uid, :name
  
  def self.from_omniauth(auth)
    find_by_provider_and_uid(auth["provider"], auth["uid"]) || create_with_omniauth(auth)
  end

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["name"]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
  
end

app/controllers/camaras_controller.rb
class CamarasController < ApplicationController
  # GET /camaras
  # GET /camaras.json
  def index
    @camaras = Camara.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @camaras }
    end
  end

  # GET /camaras/1
  # GET /camaras/1.json
  def show
    @camara = Camara.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @camara }
    end
  end

  # GET /camaras/new
  # GET /camaras/new.json
  def new
    @camara = Camara.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @camara }
    end
  end

  # GET /camaras/1/edit
  def edit
    @camara = Camara.find(params[:id])
  end

  # POST /camaras
  # POST /camaras.json
  def create
    @camara = Camara.new(params[:camara])

    respond_to do |format|
      if @camara.save
        format.html { redirect_to @camara, notice: 'Camara was successfully created.' }
        format.json { render json: @camara, status: :created, location: @camara }
      else
        format.html { render action: "new" }
        format.json { render json: @camara.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /camaras/1
  # PUT /camaras/1.json
  def update
    @camara = Camara.find(params[:id])

    respond_to do |format|
      if @camara.update_attributes(params[:camara])
        format.html { redirect_to @camara, notice: 'Camara was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @camara.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /camaras/1
  # DELETE /camaras/1.json
  def destroy
    @camara = Camara.find(params[:id])
    @camara.destroy

    respond_to do |format|
      format.html { redirect_to camaras_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/identities_controller.rb
class IdentitiesController < ApplicationController
	def new
    	@identity = env['omniauth.identity']
  	end
end

app/controllers/paginas_controller.rb
class PaginasController < ApplicationController
  # GET /paginas
  # GET /paginas.json
  def index
    @paginas = Pagina.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @paginas }
    end
  end

  # GET /paginas/1
  # GET /paginas/1.json
  def show
    @pagina = Pagina.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pagina }
    end
  end

  # GET /paginas/new
  # GET /paginas/new.json
  def new
    @pagina = Pagina.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pagina }
    end
  end

  # GET /paginas/1/edit
  def edit
    @pagina = Pagina.find(params[:id])
  end

  # POST /paginas
  # POST /paginas.json
  def create
    @pagina = Pagina.new(params[:pagina])

    respond_to do |format|
      if @pagina.save
        format.html { redirect_to @pagina, notice: 'Pagina was successfully created.' }
        format.json { render json: @pagina, status: :created, location: @pagina }
      else
        format.html { render action: "new" }
        format.json { render json: @pagina.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /paginas/1
  # PUT /paginas/1.json
  def update
    @pagina = Pagina.find(params[:id])

    respond_to do |format|
      if @pagina.update_attributes(params[:pagina])
        format.html { redirect_to @pagina, notice: 'Pagina was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pagina.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /paginas/1
  # DELETE /paginas/1.json
  def destroy
    @pagina = Pagina.find(params[:id])
    @pagina.destroy

    respond_to do |format|
      format.html { redirect_to paginas_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_url, notice: "Signed in!"
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Signed out!"
  end
  
  def failure
    redirect_to root_url, alert: "Authentication failed, please try again."
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/camaras_helper.rb
module CamarasHelper
end

app/helpers/identities_helper.rb
module IdentitiesHelper
end

app/helpers/paginas_helper.rb
module PaginasHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/camaras/_form.html.erb
<%= form_for @camara, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :ubicacion, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :ubicacion, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                camaras_path, :class => 'btn' %>
  </div>
<% end %>

app/views/camaras/edit.html.erb
<%- model_class = Camara -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/camaras/index.html.erb
<%- model_class = Camara -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:ubicacion) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @camaras.each do |camara| %>
      <tr>
        <td><%= link_to camara.id, camara_path(camara) %></td>
        <td><%= camara.ubicacion %></td>
        <td><%=l camara.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_camara_path(camara), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      camara_path(camara),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_camara_path,
            :class => 'btn btn-primary' %>

app/views/camaras/new.html.erb
<%- model_class = Camara -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/camaras/show.html.erb
<%- model_class = Camara -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:ubicacion) %>:</strong></dt>
  <dd><%= @camara.ubicacion %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              camaras_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_camara_path(@camara), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              camara_path(@camara),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/identities/new.html.erb
<h1>Nuevo usuario</h1>

<%= form_tag "/auth/identity/register" do %>
  <% if @identity && @identity.errors.any? %>
    <div class="error_messages">
      <h2><%= pluralize(@identity.errors.count, "error") %> prohibited this account from being saved:</h2>
      <ul>
      <% @identity.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= label_tag :Nombre %><br>
    <%= text_field_tag :name, @identity.try(:name) %>
  </div>
  <div class="field">
    <%= label_tag :email %><br>
    <%= text_field_tag :email, @identity.try(:email) %>
  </div>
  <div class="field">
    <%= label_tag :Contraseña %><br>
    <%= password_field_tag :password %>
  </div>
  <div class="field">
    <%= label_tag :Confirme_su_contraseña %><br>
    <%= password_field_tag :password_confirmation %>
  </div>
  <div class="actions"><%= submit_tag "Registrar" %></div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Proyecto</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="/">Sistema vigilancia</a>
      <div class="nav-collapse">
        <ul class="nav">
          <% if current_user %>
          	  <li><%= "Bienvenido " + current_user.name %></li>
 			        <li><%= link_to "Cerrar sesión", logout_path %></li>
              <% if current_user.name == "admin" %>
                <li><%= link_to "Crear una cuenta", new_identity_path %></li>
              <% end %>  
		      <% else %>
		        <li> <%= link_to "Iniciar sesión" %></li>
          <%end%>
        </ul>
      </div>
    </div>
  </div>
</div>

<div class="container-fluid">
	<%= yield %>
</div>


</body>
</html>

app/views/paginas/_form.html.erb
<%= form_for(@pagina) do |f| %>
  <% if @pagina.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pagina.errors.count, "error") %> prohibited this pagina from being saved:</h2>

      <ul>
      <% @pagina.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/paginas/edit.html.erb
<h1>Editing pagina</h1>

<%= render 'form' %>

<%= link_to 'Show', @pagina %> |
<%= link_to 'Back', paginas_path %>

app/views/paginas/index.html.erb
<h1>Listing paginas</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @paginas.each do |pagina| %>
  <tr>
    <td><%= link_to 'Show', pagina %></td>
    <td><%= link_to 'Edit', edit_pagina_path(pagina) %></td>
    <td><%= link_to 'Destroy', pagina, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Pagina', new_pagina_path %>

app/views/paginas/new.html.erb
<h1>New pagina</h1>

<%= render 'form' %>

<%= link_to 'Back', paginas_path %>

app/views/paginas/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_pagina_path(@pagina) %> |
<%= link_to 'Back', paginas_path %>